---
controller_templates:
  - name: Server publish
    project: smart-mgt
    playbook: satellite_publish.yml
    inventory: satellite
    credentials:
      - satellite
    extra_vars:
      env: Dev
    survey_enabled: true
    survey:
      name: ''
      description: ''
      spec:
        - question_name: Select Content View
          variable: content_view
          type: multiplechoice
          choices: "{{ hostvars['sat-srv.aap.smartek.ae']['foreman_content_views'] | selectattr('name', 'match', '^RHEL.*$') | map(attribute='name') | list}}"
          required: true
          
  - name: Server promote
    project: smart-mgt
    playbook: satellite_promote.yml
    inventory: satellite
    credentials:
      - satellite
    survey_enabled: true
    survey:
      name: ''
      description: ''
      spec:
        - question_name: Select Content View
          variable: content_view
          type: multiplechoice
          choices: "{{ hostvars['sat-srv.aap.smartek.ae']['foreman_content_views'] | selectattr('name', 'match', '^RHEL.*$') | map(attribute='name') | list}}"
          required: true
        - question_name: Current Lifecycle Environment
          variable: current_lifecycle_environment
          type: multiplechoice
          choices: "{{ hostvars['sat-srv.aap.smartek.ae']['lifecycle_environments'] | selectattr('name', 'match', '^RHEL.*$') | map(attribute='name') | list}}"
          required: true
        - question_name: Next Lifecycle Environment
          variable: lifecycle_environment
          type: multiplechoice
          choices: "{{ hostvars['sat-srv.aap.smartek.ae']['lifecycle_environments'] | selectattr('name', 'match', '^RHEL.*$') | map(attribute='name') | list}}"
          required: true
          
  - name: Server patch
    project: smart-mgt
    playbook: server_patch.yml
    inventory: satellite
    use_fact_cache: true
    credentials:
      - host_cred
    limit: ''
    survey_enabled: true
    survey:
      name: ''
      description: ''
      spec:
        - question_name: Select Environment
          type: multiplechoice
          variable: lifecycle_stage
          choices: "{{ hostvars['sat-srv.aap.smartek.ae']['lifecycle_environments'] | selectattr('name', 'match', '^RHEL.*$') | map(attribute='name') | list}}"
          required: true
        - question_name: Check
          type: multiplechoice
          variable: check_only
          choices:
            - 'yes'
            - 'no'
          required: true
