---
foreman_content_views:
  - name: RHEL8
    content_view: RHEL8
    content_view_update: true
    lifecycle_environments:
      - "Dev"
      - "QA"
    repos:
    - name: Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)
      releasever: 8
      product: Red Hat Enterprise Linux for x86_64
    - name: Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)
      releasever: 8
      product: Red Hat Enterprise Linux for x86_64
    - name: Red Hat Satellite Client 6 for RHEL 8 x86_64 RPMs
      product: Red Hat Enterprise Linux for x86_64
