---
- name: vm snapshot demo
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - community.vmware
  tasks:
    - name: create snapshot
      vmware_guest_snapshot:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ vcenter_datacenter }}"
        validate_certs: false
        name: bastion
        state: present
        snapshot_name: "Ansible Managed Snapshot"
        folder: "{{ vcenter_folder }}"
        description: "This snapshot is created by Ansible Playbook"
